version: 2
 
sources:
  - name: airbnb
    schema: RAW
    tables:
      - name: RAW_LISTINGS
      - name: RAW_HOSTS
      - name: RAW_REVIEWS
      - name: RAW_CUSTOMER
      - name: sales_us
 